# Generated by Django 3.1.7 on 2021-07-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210728_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_head',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_nurse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
