# Generated by Django 3.1.7 on 2021-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210909_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.IntegerField(default=736883, unique=True),
        ),
    ]
